backend:
  name: github
  branch: master
  repo: christophevx/xpcreation
media_folder: 'assets/images'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
