name: Get Facebook new activity
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'

  workflow_dispatch:
jobs:
  update_facebook:
    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: .github/workflows/facebook.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: ruby -e 'puts $:'
      - run: ruby --version
      - run: gem query --local
      - run: ls -lh
      - run: ruby ./scripts/facebookupdate.rb ${{ secrets.FACEBOOK_ID }} ${{ secrets.FACEBOOK_PAGE_ID }} ${{ secrets.FACEBOOK_ACCESS_TOKEN }} ${{ secrets.FACEBOOK_APP_SECRET }}
